# Configuration parameters for Kafka Producer
#port: ec2-34-193-153-112.compute-1.amazonaws.com:9092 #de-ny-dene-02
port: ec2-34-206-32-123.compute-1.amazonaws.com:9092 #de-ny-dene-03
# topics: [cars,users]
topics: ['cars','users']
time_buffer: 1
data_file_name: 'data/test_data_30.csv'
data_column_keys: [trip_distance,passenger_count,pickup_latitude,pickup_longitude,dropoff_latitude,dropoff_longitude]
